cloud:
  aws:
    region:
      static: eu-north-1
      auto: false
    credentials:
      access-key: access-key-should-not-be-commied-to-git-hub
      secret-key: secret-key-should-not-be-commied-to-git-hub
    end-point: 
      uri: https://sqs.eu-north-1.amazonaws.com/accountid/queuename
